# Generated by Django 2.1.15 on 2020-02-22 17:58

import django.db.models.deletion
from django.db import migrations, models

import generic_serializer.serializable_model


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.AddField(
            model_name='testmodel2',
            name='test_model3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TestModel3'),
        ),
        migrations.AddField(
            model_name='testmodel1',
            name='test_model2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TestModel2'),
        ),
    ]
